{"uuid": "5982972f-8f4c-46a3-a44c-f05f85eaf4b0", "children": ["6d3dd989-52d9-4983-baf7-c62a65ccee32"], "befores": [{"name": "setup_perfectoMobile_android", "status": "passed", "start": 1625622651532, "stop": 1625622666431}], "afters": [{"name": "setup_perfectoMobile_android::1", "status": "passed", "start": 1625622750110, "stop": 1625622750110}, {"name": "setup_perfectoMobile_android::teardown", "status": "broken", "statusDetails": {"message": "TypeError: object of type 'TypeError' has no len()\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/wlan-testing/tests/../libs/perfecto_libs/android_lib.py\", line 142, in teardown\n    reporting_client.test_stop(TestResultFactory.create_failure(e))\n  File \"/usr/local/lib/python3.8/site-packages/perfecto/test/TestResultFactory.py\", line 11, in create_failure\n    return TestResultFailure(reason, traceback, failureReason)\n  File \"/usr/local/lib/python3.8/site-packages/perfecto/test/TestResult.py\", line 32, in __init__\n    if len(self.message) > 4096:\n"}, "start": 1625622750110, "stop": 1625622773622}], "start": 1625622651532, "stop": 1625622773622}