{"uuid": "2d9a7001-8982-49b1-a496-25547acc870e", "children": ["501d75a1-9d90-4add-ad3f-45f47dc51f02", "76855446-7b24-4a7e-bc9b-f43cbb1cf982", "2c0cced1-226e-4485-9517-c4be0166b0fb", "ae1f3742-648d-43e6-890c-4c50aa788b4e", "59094aa7-e8f5-4ca1-bea1-b0325df85c97", "6cb07e22-f706-4107-acd5-98ee0b08249b", "9e12f3f1-5dca-4693-97f0-63b175a4418b", "ebd06936-40a5-4795-a69e-6e8f6a3657b4", "375e2d26-82b7-4ee2-a179-acf428c8b8ce", "3fb4d572-e318-4657-ab04-37310dc1e66e", "64e2cebb-13b2-4c19-bb4e-4a25cd92d0af", "0bd61a53-08d0-4d63-b9e4-d047c0b5f7df", "7cf64aed-4570-4ecc-820f-fdebd617204e", "274bb485-18b7-43ce-8fd1-e7cec8987e50", "fa714d0f-2f83-4f97-b47f-65fafce6972d", "d320128e-fbf1-4ac2-a9db-59741f64fd5b", "56cbf66e-344e-43a3-8c52-ed0067ac7a83", "367bdda2-7ef3-437c-8d1b-69b7d7f40d80", "bc577991-a6b5-4faa-bfa1-c8063236cba5", "c66daeb6-478c-49d8-8ed8-d2d3c8f1c11a", "fd434c70-65f8-4907-8365-e0afa1998d43", "f0de1bbf-98e2-4f65-b64f-a2e02ea3cacc", "bb9b921a-f011-41d8-9918-ba8874faf6f4", "5718d241-3615-4a59-9580-7a6301fa78e9", "46e36628-baa6-4df7-a63e-c8865de6fdce"], "befores": [{"name": "get_sdk_version", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/conftest.py\", line 264, in get_sdk_version\n    version = fixtures_ver.get_sdk_version()\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 355, in get_sdk_version\n    version = self.controller_obj.get_sdk_version()\n  File \"/wlan-testing/tests/../libs/controller/controller_2x/controller.py\", line 181, in get_sdk_version\n    resp = requests.get(uri, headers=self.make_headers(), verify=False, timeout=100)\n  File \"/usr/local/lib/python3.8/site-packages/requests/api.py\", line 75, in get\n    return request('get', url, params=params, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/api.py\", line 61, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/sessions.py\", line 542, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/sessions.py\", line 655, in send\n    r = adapter.send(request, **kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/requests/adapters.py\", line 498, in send\n    raise ConnectionError(err, request=request)\n"}, "start": 1638909591249, "stop": 1638909591288}], "start": 1638909591249, "stop": 1638909671175}