{"uuid": "3702daf4-fa5d-452a-8899-78bcc88bd625", "children": ["75242c81-f8e2-4c83-bfc5-732cf4e56157"], "befores": [{"name": "setup_perfectoMobile_android", "status": "passed", "start": 1627176594676, "stop": 1627176628297}], "afters": [{"name": "setup_perfectoMobile_android::1", "status": "passed", "start": 1627176686879, "stop": 1627176686879}, {"name": "setup_perfectoMobile_android::teardown", "status": "broken", "statusDetails": {"message": "TypeError: object of type 'TypeError' has no len()\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/wlan-testing/tests/../libs/perfecto_libs/android_lib.py\", line 142, in teardown\n    reporting_client.test_stop(TestResultFactory.create_failure(e))\n  File \"/usr/local/lib/python3.8/site-packages/perfecto/test/TestResultFactory.py\", line 11, in create_failure\n    return TestResultFailure(reason, traceback, failureReason)\n  File \"/usr/local/lib/python3.8/site-packages/perfecto/test/TestResult.py\", line 32, in __init__\n    if len(self.message) > 4096:\n"}, "start": 1627176686879, "stop": 1627176709656}], "start": 1627176594676, "stop": 1627176709656}