{"uuid": "6c9912fa-cc21-4124-b56e-47e3935bcccf", "children": ["d7aeb542-c833-4558-8f25-44c790641ce2"], "befores": [{"name": "setup_perfectoMobile_android", "status": "passed", "start": 1626485677774, "stop": 1626485711439}], "afters": [{"name": "setup_perfectoMobile_android::1", "status": "passed", "start": 1626485769746, "stop": 1626485769746}, {"name": "setup_perfectoMobile_android::teardown", "status": "broken", "statusDetails": {"message": "TypeError: object of type 'TypeError' has no len()\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/wlan-testing/tests/../libs/perfecto_libs/android_lib.py\", line 142, in teardown\n    reporting_client.test_stop(TestResultFactory.create_failure(e))\n  File \"/usr/local/lib/python3.8/site-packages/perfecto/test/TestResultFactory.py\", line 11, in create_failure\n    return TestResultFailure(reason, traceback, failureReason)\n  File \"/usr/local/lib/python3.8/site-packages/perfecto/test/TestResult.py\", line 32, in __init__\n    if len(self.message) > 4096:\n"}, "start": 1626485769746, "stop": 1626485792535}], "start": 1626485677774, "stop": 1626485792537}