{"uuid": "270bd181-99b1-404d-b2eb-2e461a555305", "children": ["83b72527-053e-474d-8bfd-41233eaca6cd"], "befores": [{"name": "setup_perfectoMobile_android", "status": "passed", "start": 1626481643204, "stop": 1626481678385}], "afters": [{"name": "setup_perfectoMobile_android::1", "status": "passed", "start": 1626481738614, "stop": 1626481738615}, {"name": "setup_perfectoMobile_android::teardown", "status": "broken", "statusDetails": {"message": "TypeError: object of type 'TypeError' has no len()\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/wlan-testing/tests/../libs/perfecto_libs/android_lib.py\", line 142, in teardown\n    reporting_client.test_stop(TestResultFactory.create_failure(e))\n  File \"/usr/local/lib/python3.8/site-packages/perfecto/test/TestResultFactory.py\", line 11, in create_failure\n    return TestResultFailure(reason, traceback, failureReason)\n  File \"/usr/local/lib/python3.8/site-packages/perfecto/test/TestResult.py\", line 32, in __init__\n    if len(self.message) > 4096:\n"}, "start": 1626481738617, "stop": 1626481762158}], "start": 1626481643204, "stop": 1626481762158}