{"uuid": "8eaed97a-c558-4bed-aa4e-e0823de6173d", "children": ["c291d8bf-3116-4631-bb96-dc69620ef8f1"], "befores": [{"name": "setup_perfectoMobile_android", "status": "passed", "start": 1626485244788, "stop": 1626485278174}], "afters": [{"name": "setup_perfectoMobile_android::1", "status": "passed", "start": 1626485336205, "stop": 1626485336205}, {"name": "setup_perfectoMobile_android::teardown", "status": "broken", "statusDetails": {"message": "TypeError: object of type 'TypeError' has no len()\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/wlan-testing/tests/../libs/perfecto_libs/android_lib.py\", line 142, in teardown\n    reporting_client.test_stop(TestResultFactory.create_failure(e))\n  File \"/usr/local/lib/python3.8/site-packages/perfecto/test/TestResultFactory.py\", line 11, in create_failure\n    return TestResultFailure(reason, traceback, failureReason)\n  File \"/usr/local/lib/python3.8/site-packages/perfecto/test/TestResult.py\", line 32, in __init__\n    if len(self.message) > 4096:\n"}, "start": 1626485336205, "stop": 1626485359651}], "start": 1626485244788, "stop": 1626485359652}