{"uuid": "cae80fb5-ff2c-403b-8a32-15cb8dc5ef98", "children": ["563e619a-5db5-47fb-b41f-7a4910dfd6e8", "5d93cc9a-c3c1-4e73-8cd4-3f85a4837aad", "6285b9c5-4115-4ccd-aeb3-bd2a8906ffbe", "b2207429-7ebe-4d40-b350-e1cabdd637d0", "c9c8a2fe-ecdb-40ef-bd9a-e4041fa49a0d", "6d0f9e28-cc41-4519-a222-185324aee755"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "socket.timeout: timed out\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/interOp/conftest.py\", line 228, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_ref,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 512, in setup_profiles\n    ap_ssh = get_apnos(get_configuration['access_point'][0], pwd=\"../libs/apnos/\", sdk=\"2.x\")\n  File \"/wlan-testing/tests/../libs/apnos/apnos.py\", line 42, in __init__\n    client = self.ssh_cli_connect()\n  File \"/wlan-testing/tests/../libs/apnos/apnos.py\", line 82, in ssh_cli_connect\n    client.connect(self.ip, username=self.username, password=self.password,\n  File \"/usr/local/lib/python3.8/site-packages/paramiko/client.py\", line 349, in connect\n    retry_on_signal(lambda: sock.connect(addr))\n  File \"/usr/local/lib/python3.8/site-packages/paramiko/util.py\", line 283, in retry_on_signal\n    return function()\n  File \"/usr/local/lib/python3.8/site-packages/paramiko/client.py\", line 349, in <lambda>\n    retry_on_signal(lambda: sock.connect(addr))\n"}, "start": 1636922769674, "stop": 1636922779689}], "start": 1636922769674, "stop": 1636922784063}