{"uuid": "5b6f19bf-fe60-40c3-adf6-b18980eba13e", "children": ["ccbfa293-93e8-45f2-9ece-5886c1055bb4", "be2284d6-1b8d-4f7c-96c8-af71bc1db414", "138e167e-a448-485f-967b-ba44d3cac22e", "cecce3df-e835-43ef-90f5-ed67ff715be7", "2e851a4c-3c0e-41b9-b3b7-825a31696c79", "ed7e3645-1398-42e0-a03f-71c3e7df536d"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "socket.timeout: timed out\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/interOp/conftest.py\", line 228, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_ref,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 512, in setup_profiles\n    ap_ssh = get_apnos(get_configuration['access_point'][0], pwd=\"../libs/apnos/\", sdk=\"2.x\")\n  File \"/wlan-testing/tests/../libs/apnos/apnos.py\", line 42, in __init__\n    client = self.ssh_cli_connect()\n  File \"/wlan-testing/tests/../libs/apnos/apnos.py\", line 82, in ssh_cli_connect\n    client.connect(self.ip, username=self.username, password=self.password,\n  File \"/usr/local/lib/python3.8/site-packages/paramiko/client.py\", line 349, in connect\n    retry_on_signal(lambda: sock.connect(addr))\n  File \"/usr/local/lib/python3.8/site-packages/paramiko/util.py\", line 283, in retry_on_signal\n    return function()\n  File \"/usr/local/lib/python3.8/site-packages/paramiko/client.py\", line 349, in <lambda>\n    retry_on_signal(lambda: sock.connect(addr))\n"}, "start": 1636922797358, "stop": 1636922807366}], "start": 1636922797358, "stop": 1636922811257}