{"uuid": "0ce0a9c5-fb0d-4724-b9cb-a79e3bc115cd", "children": ["8b0e3013-6716-4b82-b647-e5743678f50c"], "befores": [{"name": "fixtures_ver", "status": "broken", "statusDetails": {"message": "_pytest.outcomes.Exit: unable to communicate to ControllerInvalid response code.\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/conftest.py\", line 646, in fixtures_ver\n    obj = Fixtures_2x(configuration=get_configuration)\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 56, in __init__\n    pytest.exit(\"unable to communicate to Controller\" + str(e))\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/outcomes.py\", line 115, in exit\n    raise Exit(msg, returncode)\n"}, "attachments": [{"name": "Controller Instantiation Failed: ", "source": "c0245896-af64-4a32-8364-44577062edcb-attachment.attach"}], "start": 1637183198663, "stop": 1637183198716}], "start": 1637183198663, "stop": 1637183203177}