{"uuid": "f9a902d0-4723-4086-b2e1-06c50dfdd693", "children": ["0b779f58-48c6-42cf-9186-ed626299fac5"], "befores": [{"name": "setup_perfectoMobile_android", "status": "passed", "start": 1627006301868, "stop": 1627006336218}], "afters": [{"name": "setup_perfectoMobile_android::1", "status": "passed", "start": 1627006435921, "stop": 1627006435921}, {"name": "setup_perfectoMobile_android::teardown", "status": "broken", "statusDetails": {"message": "TypeError: object of type 'TypeError' has no len()\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/wlan-testing/tests/../libs/perfecto_libs/android_lib.py\", line 142, in teardown\n    reporting_client.test_stop(TestResultFactory.create_failure(e))\n  File \"/usr/local/lib/python3.8/site-packages/perfecto/test/TestResultFactory.py\", line 11, in create_failure\n    return TestResultFailure(reason, traceback, failureReason)\n  File \"/usr/local/lib/python3.8/site-packages/perfecto/test/TestResult.py\", line 32, in __init__\n    if len(self.message) > 4096:\n"}, "start": 1627006435921, "stop": 1627006463448}], "start": 1627006301868, "stop": 1627006463448}