{"uuid": "2c6b92be-be2d-455a-a556-eb568d827170", "children": ["010e94f4-2ee9-49b7-b556-60c46d41260e", "aa608259-c1d9-43a1-9f41-8aaa85a83f2e", "a8fe515e-5b18-4027-b8c9-6f9e5ae6b63c", "3de1fa44-c4b4-4067-b93c-980a92a16e9a", "56338363-19d2-43bd-9af2-4a41189fbe19", "adff7d5e-5db0-4d93-93b1-cd0f016abd14"], "befores": [{"name": "setup_profiles", "status": "broken", "statusDetails": {"message": "socket.timeout: timed out\n", "trace": "  File \"/usr/local/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/wlan-testing/tests/e2e/interOp/conftest.py\", line 228, in setup_profiles\n    return_var = fixtures_ver.setup_profiles(request, param, setup_controller, testbed, get_equipment_ref,\n  File \"/wlan-testing/tests/fixtures_2x.py\", line 512, in setup_profiles\n    ap_ssh = get_apnos(get_configuration['access_point'][0], pwd=\"../libs/apnos/\", sdk=\"2.x\")\n  File \"/wlan-testing/tests/../libs/apnos/apnos.py\", line 42, in __init__\n    client = self.ssh_cli_connect()\n  File \"/wlan-testing/tests/../libs/apnos/apnos.py\", line 82, in ssh_cli_connect\n    client.connect(self.ip, username=self.username, password=self.password,\n  File \"/usr/local/lib/python3.8/site-packages/paramiko/client.py\", line 349, in connect\n    retry_on_signal(lambda: sock.connect(addr))\n  File \"/usr/local/lib/python3.8/site-packages/paramiko/util.py\", line 283, in retry_on_signal\n    return function()\n  File \"/usr/local/lib/python3.8/site-packages/paramiko/client.py\", line 349, in <lambda>\n    retry_on_signal(lambda: sock.connect(addr))\n"}, "start": 1637700625249, "stop": 1637700635260}], "start": 1637700625249, "stop": 1637700639144}